[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true


[workspace.package]
version = "0.1.0"
authors = ["VaibhavArora19"]
edition = "2024"
rust-version = "1.88"
license = "MIT or Apache-2.0"
publish = false

[workspace]
members = ["crates/*", "bin/executor"]
resolver = "3"
